# .github/workflows/locust.yml
name: Locust Performance Test

on:
  push:
    branches:
      - add-workflow

jobs:
  locust:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requirements.txt

      - name: Run Locust
        run: locust -f src/test_scripts/test_get_api.py --headless -u 100 -r 10 --run-time 20m --host https://api.simplehash.com
