name: Second Workflow

on:
  workflow_dispatch:  # This allows you to manually trigger the workflow

jobs:
  run_first_workflow:
    name: Run First Workflow
    uses: jacqueline-57b/hub-perf-test/.github/workflows/test1.yml@main


  use_output:
    runs-on: ubuntu-latest
    needs: [run_first_workflow]

    steps:
      - name: Access Output from First Workflow
        run: |
          echo ${{ toJSON(needs.run_first_workflow.outputs) }}
          echo "The generated value from the first workflow is: ${{ needs.run_first_workflow.outputs.generated_value }}"
