name: First Workflow

on:
  workflow_dispatch:  # This allows you to manually trigger the workflow

  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate Output
        id: generate_output
        run: |
          OUTPUT_VALUE="jacqueline-test-1"
          echo "OUTPUT_VALUE=${OUTPUT_VALUE}" >> $GITHUB_ENV
          echo "generated_value=${OUTPUT_VALUE}" >> $GITHUB_OUTPUT

    outputs:
      run: |
        echo "The generated value is: ${{ env.OUTPUT_VALUE }}"
        echo "The generated value is: ${{ steps.generate_output.outputs.generated_value }}"

      output_value: ${{ env.OUTPUT_VALUE }}
      generated_value: ${{ steps.generate_output.outputs.generated_value }}